<?php

namespace app\models;
use yii\web\UploadedFile;
use Yii;

/**
 * This is the model class for table "products".
 *
 * @property int $id
 * @property int $category_id
 * @property string $name
 * @property string $description
 * @property string $img
 * @property int $price
 * @property string $amount
 *
 * @property Category $category
 */
class Products extends \yii\db\ActiveRecord
{
    public $file;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'products';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['category_id', 'price', 'amount'], 'integer'],
            [['name'], 'required'],
            [['description'], 'string'],
            [['name'], 'string', 'max' => 255],
            ['img', 'string'],
            ['file', 'file', 'extensions' => ['svg', 'jpg', 'png']],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => Category::className(), 'targetAttribute' => ['category_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'category_id' => Yii::t('app', 'Category ID'),
            'name' => Yii::t('app', 'Name'),
            'description' => Yii::t('app', 'Description'),
            'img' => Yii::t('app', 'Img'),
            'price' => Yii::t('app', 'Price'),
            'amount' => Yii::t('app', 'Amount'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }

    public function getImage()
    {
        return $this->img;
    }

    public function upload()
    {
        if ($this->validate()) {

            $filename = 'uploads/' . $this->file->baseName . Yii::$app->security->generateRandomString(3) . '.' . $this->file->extension;

            $this->file->saveAs($filename);
            $this->img = '/' . $filename;

            return true;
        } else {
            return false;
        }
    }

    public function beforeSave($insert)
    {
        $this->file = \yii\web\UploadedFile::getInstance($this, 'file');
        $this->upload();

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
